### ISSUE TITLE
pip install "git+https://github.com/facebookresearch/pytorch3d.git"   falied

### ISSUE THREAD

**Issue by wuxiaofei01** [stevenlsw/contactgen#1]
Dear authors, first of all thank you for your very good work. However, I ran into some problems while trying to reproduce your work.
When I executed "pip install "git+https://github.com/facebookresearch/pytorch3d.git"", I found an error.

   note: This error originates from a subprocess, and is likely not a problem with pip.
   ERROR: Failed building wheel for pytorch3d
   Running setup.py clean for pytorch3d
Failed to build pytorch3d
ERROR: Could not build wheels for pytorch3d, which is required to install pyproject.toml-based projects

May I ask the author, how to solve this problem?

**Comment by stevenlsw** [comment]
Hi, you could refer to https://github.com/facebookresearch/pytorch3d/blob/main/INSTALL.md, hope that helps.

**Comment by wuxiaofei01** [comment]
Hello,
Thank you once again for your work. I have been trying to keep up with your progress, but due to environmental issues, I have been unable to make any progress myself.
I have successfully set up pytorch3d, but I am facing difficulties in building due to issues with point_lib.
I was wondering if it would be possible for you to provide a **Docker link**? If so, I would greatly appreciate your contribution.
```
      raise RuntimeError(message) from e
      RuntimeError: Error compiling objects for extension
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for pointnet2
  Running setup.py clean for pointnet2
Failed to build pointnet2
ERROR: Could not build wheels for pointnet2, which is required to install pyproject.toml-based projects
```

**Comment by stevenlsw** [comment]
Hi, the code requires pytorch to compile, may I ask which version of pytorch are you using?

**Comment by wuxiaofei01** [comment]
> Hi, the code requires pytorch to compile, may I ask which version of pytorch are you using?

```
import torch
import pytorch3d
print(torch.__version__)
print(torch.cuda.is_available())

```
2.1.1+cu118
True

Thank you very much for the author's reply. The above is the output of my program.

**Comment by wuxiaofei01** [comment]
i find the solution , in pytorch3d ,  cann't **conda install -c bottler nvidiacub**,
