### ISSUE TITLE
The problem about dataset 

### ISSUE THREAD

**Issue by cgsmalcloud** [stevenlsw/contactgen#2]
Dear authors,
First and foremost, I would like to extend my sincere gratitude for sharing your work on GitHub.
I am reaching out to inquire about certain aspects of the dataset used in your published code, specifically regarding the preprocessing of the grabnet dataset. My questions are as follows:
1、In the code that you have made available, I noticed that the preprocessing is done on a subset of the grabnet dataset. Could you please confirm if the comparisons made in your paper also utilized the same subset of the dataset?
2、If the full grabnet dataset was used in your research paper, I would be interested to know the configuration of the training equipment you employed for this purpose.

Your insights on these matters would be incredibly helpful for my understanding and further exploration of your work.
Thank you in advance for your time and response.
Best regards

**Comment by stevenlsw** [comment]
Hi, we follow the same evaluation setting as https://github.com/korrawe/halo on Grab and HO3D dataset, we remove those redundant frames (same grasping pose of each object) in each training sequence, hope that is clear.
