### ISSUE TITLE
Contact map in inference

### ISSUE THREAD

**Issue by antonagafonov** [stevenlsw/contactgen#4]
Hi,
Can the contact map of a grabbed object be exported in inference?

Thanks

**Comment by stevenlsw** [comment]
Hi, you could visualize in point cloud by Open3d.

**Comment by zy123456123** [comment]
Hi, How to visualize the Direction Map and Part Map?

**Comment by stevenlsw** [comment]
Hi, given a point, a part map indicates a part segmentation label, so you could vis it as point cloud segmentation; for direction map, it is a unit vector, you could visualize it as point cloud surface normal or use colorwheel to visualize the first two components of it, just like [visualizing optical flow](https://github.com/tomrunia/OpticalFlow_Visualization)
