### ISSUE TITLE
Can the data format use mano parameters?

### ISSUE THREAD

**Issue by wuxiaofei01** [stevenlsw/contactgen#5]
Dear author,

Greetings. Your work has truly presented an excellent solution. I have noticed that the parameters format used in your team's code differs from that of **MANO（61 param）**. May I kindly inquire if you would be able to offer insights or guidance on this matter? Your assistance would be immensely appreciated.

Best regards,

**Comment by stevenlsw** [comment]
Hi, they should contain the same number of parmeters as original Mano,  Mano global transformation(3) + Mano pose (16*3) + shape (10)

**Comment by wuxiaofei01** [comment]
Thanks to the author for the reply. I will also provide my solution ideas here.
According to the author's preprocessed data set, you can use 
```
def convert_rotmat_to_euler(rotmat):
    r = Rotation.from_matrix(rotmat.reshape(-1, 3, 3))
    euler = r.as_euler('xyz')
    euler = euler.reshape(rotmat.shape[:-2] + (3,))
    return euler
def convert_euler_to_rotmat(euler):
    euler_list = [euler[i].tolist() for i in range(euler.shape[0])]
    rot_matrices = [Rotation.from_euler('xyz', angles).as_matrix() for angles in euler_list]
    rotmat_numpy = np.stack(rot_matrices)
    rotmat_torch = torch.tensor(rotmat_numpy, dtype=torch.float32)
    return rotmat_torch
```
to simplify the rotation matrix.
