### ISSUE TITLE
Contact Ratio ，  Entropy ， Cluster Size 

### ISSUE THREAD

**Issue by wuxiaofei01** [stevenlsw/contactgen#7]
Hello author, I would like to ask how the three metric parameters in the question are calculated? Could you please provide the code?

**Comment by stevenlsw** [comment]
Hi, thanks for your interest in our work, for evaluation we follow the same setting as [HALO](https://github.com/korrawe/halo). Please let me know if you have any other questions.

**Comment by wuxiaofei01** [comment]
hello ， i want to know how to evaluation HO3D dataset？there is no details。maybe just evaluate 
`['003_cracker_box', '004_sugar_box', '006_mustard_bottle',
              '010_potted_meat_can', '011_banana', '019_pitcher_base', '021_bleach_cleanser', '025_mug', '035_power_drill', '037_scissors']`
just once？or some details which i missed？

**Comment by wuxiaofei01** [comment]
Halo is all you need!

> hello ， i want to know how to evaluation HO3D dataset？there is no details。maybe just evaluate `['003_cracker_box', '004_sugar_box', '006_mustard_bottle', '010_potted_meat_can', '011_banana', '019_pitcher_base', '021_bleach_cleanser', '025_mug', '035_power_drill', '037_scissors']` just once？or some details which i missed？
