### ISSUE TITLE
HO3D dataset

### ISSUE THREAD

**Issue by wuxiaofei01** [stevenlsw/contactgen#8]
hello,author:
    We have been paying attention to your work recently. I was looking at the test results of ho3d and found that GF and TTA are both based on the obman data set. But it did not explain what data sets grabnet, GALO, and contactgen are based on.
Is it based on **obman**? Or is it based on **grab datase**t?

**Comment by stevenlsw** [comment]
Hi, this is the generalization results, HO-3D is not included at training time for all methods, thus for all methods the dataset is considered out-of-domain data.

**Comment by wuxiaofei01** [comment]
> Following previous work [30], we perform K-means clustering on **3D hand keypoints** for all methods.

Hello, author. Recently I encountered a problem during evaluation. When evaluating the cluster size, I found that the order of magnitude was wrong. This may be because my param is not consistent with your work.
What are the 3D hand keypoints here?
Thank you very much for your reply

**Comment by stevenlsw** [comment]
Hi, for fair comparison, we keep the keypoints same  in HALO, the evaluation script is adapted from [here](https://github.com/korrawe/halo/blob/main/halo/evaluate_cluster.py#L66)

**Comment by jacky-chen-dev** [comment]
hello, how did you modify the evaluation script based on the halo one? I saw that halo stored hand keypoints but ContactGen stores obj file from Trimesh. Thank you!

**Comment by stevenlsw** [comment]
Hi,

Thanks for the interest. We evaluate follow the same setting as HALO, you could easily get hand Mano kpts from the [Mano layer output](https://github.com/stevenlsw/contactgen/blob/master/manopth/manolayer.py#L232) and use `joints = global_transf[:, :, :3, 3]` to evaluate the diversity and cluster size, other metrics requires the mesh file.

**Comment by jacky-chen-dev** [comment]
> Hi,
> 
> Thanks for the interest. We evaluate follow the same setting as HALO, you could easily get hand Mano kpts from the [Mano layer output](https://github.com/stevenlsw/contactgen/blob/master/manopth/manolayer.py#L232) and use `joints = global_transf[:, :, :3, 3]` to evaluate the diversity and cluster size, other metrics requires the mesh file.

Thank you for the reply !
