### ISSUE TITLE
How to obtain evaluation metric?

### ISSUE THREAD

**Issue by zy123456123** [stevenlsw/contactgen#9]
hi！
 when retrain and eval the code, calculate intersection  volumn of the two inputs meshes on the GRAB dataset, set scale = 1
    res = 0.005 ，get  result  vol cm3=2.42. Why did get such a result？
![图片](https://github.com/stevenlsw/contactgen/assets/76393070/e304bcbb-57ff-450e-bd06-803c0b144222)

**Comment by stevenlsw** [comment]
Hi, thanks for your interest in the work. for evaluation code, we follow [HALO](https://github.com/korrawe/halo/) setting and voxelizd the meshes into 1mm3 cubes and measuring overlapping voxel.

**Comment by wuxiaofei01** [comment]
Hello author, I also encountered the eval problem. I tried to use the HALO code to reproduce it and found that the cluster size was only about **3.3, which was far from the 5.0 in the paper**.
```
        global_pose, mano_pose, mano_shape, mano_trans = optimize_pose(hand_model, mano_layer, obj_verts, contacts_object, partition_object, uv_object,
                                                                       w_contact=args.w_contact, w_pene=args.w_pene, w_uv=args.w_uv) 
        hand_verts, hand_frames = mano_layer(torch.cat((global_pose, mano_pose), dim=1), th_betas=mano_shape, th_trans=mano_trans)


        grab_to_mano = [0, 13, 14, 15, 16, 1, 2, 3, 17, 4, 5, 6, 18, 10, 11, 12, 19, 7, 8, 9, 20]
        hand_kps = hand_verts[: , grab_to_mano , :]

        '''cluster'''
        is_right_vec = torch.ones(
            hand_kps.shape[0], device=hand_kps.device)

        hand_kps = convert_joints(
            hand_kps, source='mano', target='biomech')

        hand_kps_after, _ = transform_to_canonical(hand_kps, is_right_vec)
        hand_kps_after = convert_joints(
            hand_kps_after, source='biomech', target='mano')

        for count, kps_flat in enumerate(hand_kps_after):
            cluster2.append(kps_flat.reshape(-1).detach().cpu().numpy())
    
        cluster_array_2 = np.array(cluster2)
        entropy_2, cluster_size_2 = diversity(cluster_array_2, cls_num=20)
```
Could the author consider providing the code you used?

**Comment by stevenlsw** [comment]
Hi, have you converted the joints to cm (the output is of Mano layer is in meter) and how many samples are you using

**Comment by wuxiaofei01** [comment]
> Hi, have you converted the joints to cm (the output is of Mano layer is in meter) and how many samples are you using

Now I tried converting verts to cm, I also tried sampling times with 10 and 20 times in the HO3D dataset.But I found that the results were all around 3.4.

first
```
        contacts_object, partition_object, uv_object = sample_results
        contacts_object = contacts_object.squeeze()
        partition_object = partition_object.argmax(dim=-1)
        global_pose, mano_pose, mano_shape, mano_trans = optimize_pose(hand_model, mano_layer, obj_verts, contacts_object, partition_object, uv_object,
                                                                       w_contact=args.w_contact, w_pene=args.w_pene, w_uv=args.w_uv) 
        hand_verts, hand_frames = mano_layer(torch.cat((global_pose, mano_pose), dim=1), th_betas=mano_shape, th_trans=mano_trans)

        grab_to_mano = [0, 13, 14, 15, 16, 1, 2, 3, 17, 4, 5, 6, 18, 10, 11, 12, 19, 7, 8, 9, 20]
        hand_kps = hand_verts[: , grab_to_mano , :] * 100
        for kps_idx in hand_kps:
            kps_list_npy.append(kps_idx.detach().cpu().numpy())
        np.save("kps_list.npy",kps_list_npy)
```

```
kps_all_list = []
hand_kps_list = np.load('kps_list.npy')
for hand_kps in hand_kps_list:
    hand_kps_before = hand_kps

    hand_kps = torch.from_numpy(hand_kps).unsqueeze(0)
    is_right_vec = torch.ones(hand_kps.shape[0], device=hand_kps.device)

    hand_kps = convert_joints(hand_kps, source='mano', target='biomech')

    hand_kps_after, _ = transform_to_canonical(hand_kps, is_right_vec)
    hand_kps_after = convert_joints(hand_kps_after, source='biomech', target='mano')
    hand_kps = hand_kps_after.squeeze(0).numpy()

    kps_flat = hand_kps.reshape(-1)
    kps_all_list.append(kps_flat)

kps_all = np.stack(kps_all_list, axis=0)  # [120, 63]
print(len(kps_all))
cls_num = 20
entropy, dist = diversity(kps_all, cls_num=cls_num)
print(" entropy :", entropy)
print(" dist :", dist)
```

**Comment by stevenlsw** [comment]
Hi, in your provided code, you are evaluating the hand vertices, for diversity we evaluate hand joints, not hand verts (768), this is the function to convert from MANO output to hand joints (21)
```
def verts2kps(hand_verts, hand_frame):
    jtr = hand_frame[:, :3, 3]
    tips = hand_verts[[745, 317, 444, 556, 673]]
    jtr = np.concatenate([jtr, tips], 0)
    return jtr # "halo order"
```
please further double check to make sure the inputs are correct for evaluation.

**Comment by zy123456123** [comment]
hi,for evaluation code, followed halo setting and voxelizd the meshes into 1mm3 cubes.
` object_list = ['binoculars', 'camera', 'fryingpan', 'mug', 'toothpaste', 'wineglass']
    mesh_dir = '../exp/results/'

    for obj_idx, object_type in enumerate(object_list):
        print()
        obj_dir = '../grab_data/obj_meshes'
        obj_mesh_filename = os.path.join(obj_dir, '%s.ply' % object_type)

        vol_list = []
        mesh_dist_list = []
        n_sample = 20
        for idx in range(n_sample):
            # hand_mesh_filename = os.path.join(obj_dir, 'obj%03d_h%03d.obj' % (obj_idx, idx))
            # Initial prediction
            hand_mesh_filename = os.path.join(mesh_dir, object_type, 'grasp_%s.obj' % idx)
            # Refine
            # hand_mesh_filename = os.path.join(obj_dir, '%s_h%03d_refine.obj' % (object_type, idx))

            print(hand_mesh_filename)
            print(obj_mesh_filename)
            hand = trimesh.load(hand_mesh_filename, process=False)
            hand = seal(hand)
            object = trimesh.load(obj_mesh_filename, process=False)

            vol, mesh_dist = intersection_eval(hand, object, res=0.001, scale=0.01)
            vol_list.append(vol)
            mesh_dist_list.append(mesh_dist)
            print(vol)

        print(" -- ", object_type, " -- ")
        print(" vol cm3: ", np.mean(vol_list))
        print(" inter dist cm: ", np.mean(mesh_dist_list))
        print(" contact ratio: ", np.mean(np.array(mesh_dist_list) < 0))

        vol_clip = np.clip(vol_list, 0, 20)
        plt.figure()
        plt.hist(vol_clip, bins=20, range=(0, 21))
        plt.show()
`
` def intersection_eval      # From (m) to (mm) 
    return i_v * 1e9, mesh_mesh_distance * 1e3`
 I  encountered the problem :   ValueError: Parameter p has shape 0 at dimension 0. Expected p.shape[0] > 0.

**Comment by zy123456123** [comment]
hi! for evaluation code, i followed [HALO](https://github.com/korrawe/halo/) setting and voxelizd the meshes into 1mm3 cubes.
But i encountered the  problem: ValueError: Parameter p has shape 0 at dimension 0. Expected p.shape[0] > 0. Why?
`object_list = ['binoculars', 'camera', 'fryingpan', 'mug', 'toothpaste', 'wineglass']
    mesh_dir = '../exp/results/'

    for obj_idx, object_type in enumerate(object_list):
        print()
        obj_dir = '../grab_data/obj_meshes'
        obj_mesh_filename = os.path.join(obj_dir, '%s.ply' % object_type)

        vol_list = []
        mesh_dist_list = []
        n_sample = 20
        for idx in range(n_sample):
            # hand_mesh_filename = os.path.join(obj_dir, 'obj%03d_h%03d.obj' % (obj_idx, idx))
            # Initial prediction
            hand_mesh_filename = os.path.join(mesh_dir, object_type, 'grasp_%s.obj' % idx)
            # Refine
            # hand_mesh_filename = os.path.join(obj_dir, '%s_h%03d_refine.obj' % (object_type, idx))

            print(hand_mesh_filename)
            print(obj_mesh_filename)
            hand = trimesh.load(hand_mesh_filename, process=False)
            hand = seal(hand)
            object = trimesh.load(obj_mesh_filename, process=False)

            vol, mesh_dist = intersection_eval(hand, object, res=0.001, scale=0.01)
            vol_list.append(vol)
            mesh_dist_list.append(mesh_dist)
            print(vol)

        print(" -- ", object_type, " -- ")
        print(" vol cm3: ", np.mean(vol_list))
        print(" inter dist cm: ", np.mean(mesh_dist_list))
        print(" contact ratio: ", np.mean(np.array(mesh_dist_list) < 0))

        vol_clip = np.clip(vol_list, 0, 20)
        plt.figure()
        plt.hist(vol_clip, bins=20, range=(0, 21))
        plt.show()`

`# From (m) to (mm)
    return i_v * 1e9, mesh_mesh_distance * 1e3`

**Comment by zy123456123** [comment]
@wuxiaofei01  hi！Can you obtain a consistent evaluation result as stated in the paper, which is a Penetration Volume of 2.72 on the Grab dataset. Can you share your code? Thank you.

**Comment by wuxiaofei01** [comment]
@zy123456123 
Unfortunately, I did not get the results in the paper.
